### PR TITLE
Use std::filesystem or ghc::filesystem instead of boost:filesystem

### PR DESCRIPTION
**Pull request by dmacvicar**
Similar to what is being done in [artist](https://github.com/cycfi/artist/tree/windows_port/lib/include/artist)

Possibly obsoletes and supersedes https://github.com/cycfi/elements/pull/79

### CODE REVIEW

**Comment by djowel** [comment]
Nice!

**Comment by djowel** [comment]
Develop should be good now. See 115dca5dfbda41f81bc26d72f9c1561cb01fb6a6.

**Comment by dmacvicar** [comment]
Not really. We are still having json depending on boost. I will submit a PR to make it take std::filesystem or ghc::filesystem from infra.

**Comment by djowel** [comment]
> Not really. We are still having json depending on boost. I will submit a PR to make it take std::filesystem or ghc::filesystem from infra.

Have you updated json to the latest from 'master' ? https://github.com/cycfi/json/commit/fb4e03c4a83a2da2c931a2bf84f2c19d2bda531b

The latest C.I. looks good to me: https://github.com/cycfi/elements/actions/runs/71463635

**Comment by dmacvicar** [comment]
>The latest C.I. looks good to me: https://github.com/cycfi/elements/actions/runs/71463635

It does! sorry for all the trouble.

**Comment by djowel** [comment]
> It does! sorry for all the trouble.

The pleasure is all mine. I suppose now we've satisfied one of your requirements: easy deployment without any unnecessary hassle ? :-)

**Comment by dmacvicar** [comment]
Yes. I will start integrating the develop branch in my source and CI and see if I can replace nanogui.

**Pull request merged**
