### PR TITLE
Adapt docs files to be viewed locally

### PR DESCRIPTION
**Pull request by redtide**
I haven't a way to test this online since GH permits pages only from master branch, locally it's correct, I'm not sure about the relative links if they will work correctly as is or they needs a `| relative_url` addition later.
I've added also a simple README file, some more .gitignored files (VSCode works good with Jekyll) and a convenient bash script to install and run things under a Linux environment (locally at least here on ArchLinux using RVM).
The added Gemfile is required to install bundler and other dependencies required to run Jekyll.
See #130.

### CODE REVIEW

**Comment by djowel** [comment]
OK, this works. verified... I had to change ruby to "2.6.0" though, because that is what I do locally when working on the docs. Would you have a problem with that?

**Comment by djowel** [comment]
Update: actually wouldn't it be better if we don't specify ruby "2.6.0"? That is what I originally have in my local setup.

**Comment by djowel** [comment]
Update: 

- I had to fix the README.md to. The website will be available at <http://localhost:4000/elements/>.
- I had to fix jeckyl.sh, removing --host=0.0.0.0 for the README.md to be correct. Is there a problem on Windows? Why did you have --host=0.0.0.0?

**Comment by redtide** [comment]
> actually wouldn't it be better if we don't specify ruby "2.6.0"? That is what I originally have in my local setup.

As specified in the README, I just try to keep the same versions as used by GitHub. This to avoid conflicts, so for that reason I've installed RVM to keep all the required Ruby versions. I can just imagine that some day the user that needs to run the pages could have a new version that will not work (well) with the old Jekyll used there or try to update Jekyll and have troubles because deprecated APIs. I think that happened to me at least 2 times, so I have become paranoid because of that :-D

> * I had to fix the README.md to. The website will be available at http://localhost:4000/elements/.

Sorry, I forgot about the baseurl.

> * I had to fix jeckyl.sh, removing --host=0.0.0.0 for the README.md to be correct. Is there a problem on Windows? Why did you have --host=0.0.0.0?

That should make the website accessible also from other machines in the LAN.

**Pull request merged**
