### PR TITLE
fix leaks in canvas by RAIIing cairo patterns

### PR DESCRIPTION
**Pull request by Xeverous**

### CODE REVIEW

**Comment by djowel** [comment]
I think I am OK with this contribution, except for one thing: I think I can agree on a joint copyright only if there's significant edits to certain file(s). The typical metric is at least half the size of the file in terms of LOC. I know LOC is not really a good metric, considering other important factors such as design, but it's the only reasonable metric for such things, and the policy has worked in the past with the libraries I authored with other contributors, esp. Boost.

If you agree, I'm OK merging this.

**Comment by Xeverous** [comment]
I'm fine with it. But IIRC somewhere earlier you wrote the metric to be 20%, not 50%. Want me to revert the copyright line?

**Comment by djowel** [comment]
> I'm fine with it. But IIRC somewhere earlier you wrote the metric to be 20%, not 50%. Want me to revert the copyright line?

Where did I write that ;-) ?

**Comment by Xeverous** [comment]
> Where did I write that ;-) ?

Can't find it in the issues, this had to be on a voice call before I implemented progress bar because that's my first copyright.

**Comment by Xeverous** [comment]
So want me to revert the copyright line?

**Comment by djowel** [comment]
In the interest of moving forward, I decided to  merge this and the other RAII PR. I am not sure when I will get enought time to investigate further, and I understand that this is a pressing issue. Running the sanitizers on MacOS does not report the errors for this and the other PR, perhaps due to some mix of #ifdefs I haven't investigated enough.

Here are two requests though: 

1. The proper copyright notice is as follows:
Copyright (c) 2016-2020 Joel de Guzman
Copyright (c) 2020 Michal Urbanski

Can you please correct this one and the other files that you contributed to?

2. Let's meet halfway. Next time, we can settle for a metric of > 35% LOC to be eligible for joint copyright on files. I suppose that is reasonable?

Cheers and THANK YOU VERY MUCH for your contributions. I can't stress enough how valuable they are!

**Comment by Xeverous** [comment]
> Can you please correct this one and the other files that you contributed to?

Yes, I will check my history and correct them. From your experience working in boost - is there any general guideline for people with names that are not pure latin? Do people strip diacritics or preserve them? C++ sources are expected to be UTF-8 anyway and implementations support unicode, especially in comments.

> Let's meet halfway. Next time, we can settle for a metric of > 35% LOC to be eligible for joint copyright on files. I suppose that is reasonable?

I think yes.

> Let's meet halfway. Next time, we can settle for a metric of > 35% LOC to be eligible for joint copyright on files. I suppose that is reasonable?

You know, it all started because I wanted a modern C++ GUI library with certain features and just wanted to add tabs to elements. But it seems I will stay here even longer...

**Comment by djowel** [comment]
> From your experience working in boost - is there any general guideline for people with names that are not pure latin? Do people strip diacritics or preserve them? C++ sources are expected to be UTF-8 anyway and implementations support unicode, especially in comments.

Please use UTF-8. All modern tools support it. Here was a recent (just today!) "issue" in the Spirit: 

https://github.com/boostorg/spirit/issues/612#issuecomment-642333176

**Pull request merged**
