### PR TITLE
split focus(focus_request) into 3 functions

### PR DESCRIPTION
**Pull request by Xeverous**
focus_request::wants_focus => bool is_focusable() const
focus_request::begin_focus => void begin_focus()
focus_request::end_focus   => void end_focus()

The return value of focus(focus_request) with focus_request !=
focus_request::wants_focus was never used. This function has been
changed to a boolean function and other 2 enums were split into
separate functions returning void.

### CODE REVIEW

**Comment by Xeverous** [comment]
Please check new `composite_base` and `deck_element` implementations. I'm not sure if I got their behavior right.

**Comment by djowel** [comment]
Please rename `is_focusable` to `wants_focus`

**Comment by djowel** [comment]
Other than `wants_focus`, it looks good, but to be sure, let's push it to another branch so i can have a closer look. (moved target to split-focus branch)

**Comment by Xeverous** [comment]
This PR was made before CMake patches got into develop. Since you wanted to change the PR, I rebased the branch and rewritten the commit. You might want to update the `split-focus` branch HEAD.

**Comment by djowel** [comment]
This has been merged to develop with some minor fixes

**Pull request merged**
