### PR TITLE
Implemented logarithmic slider ticks

### PR DESCRIPTION
**Pull request by klytje**
I implemented a new element `slider_marks_log` and showcase it in the `range_slider` example. 

I couldn't figure out how to do this correctly while limiting myself to the original `<size, num_divs, major_divs>` template, so I switched it around (for this element only) to `<size, major_divs, minor_divs>` instead. For consistency I think either the normal `slider_marks` element should also be updated with this, or alternatively remove the `minor_divs` template from this new element and hardcode it to `10`. I don't see any reason to use a different number than this anyway.

### CODE REVIEW

**Comment by djowel** [comment]
Cool! I've been thinking about that this morning!

**Comment by djowel** [comment]
Screenshots please! :-)

**Comment by klytje** [comment]
[Screencast from 12-06-2023 07:47:17 PM.webm](https://github.com/cycfi/elements/assets/16706862/10bb4edf-5825-4855-a825-8890acb9e248)

Now that I look at it, I think the example could use a little bit of polish with some titles and sections maybe

**Comment by djowel** [comment]
Here's a suggestion:

1. Rewrite `slider_marks` with the updated template params, along with `slider_marks_element`.
2. Rename it to `slider_marks_lin` and `slider_marks_lin_element`
3. Write a forwarding function and alias template `slider_marks` and `slider_marks_element` in terms of `slider_marks_lin` and `slider_marks_lin_element`.
4. Mark these as deprecated with a message referring to the new API.
5. Have the examples use the new API.

**Comment by djowel** [comment]
> @redtide is there a way to swash the commits posthoc via github?

Ah seems there is: https://bit.ly/3uU2EPP

**Comment by djowel** [comment]
> > @redtide is there a way to swash the commits posthoc via github?
> 
> Ah seems there is: https://bit.ly/3uU2EPP

Didn't know it was there all along!

image

**Pull request merged**
