### PR TITLE
Merge master to get C.I. in develop branch

### PR DESCRIPTION
**Pull request by dmacvicar**
Merge the CI support into the develop branch.

Perhaps we even see some compile errors from the latest changes in this very same PR CI run.

### CODE REVIEW

**Comment by dmacvicar** [comment]
Ok. One error is:

```
../lib/include/elements/detail/filesystem.hpp:27:11: fatal error: 'ghc/filesystem.hpp' file not found
# include <ghc/filesystem.hpp>
          ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Which means the CI is probably not checking out the submodules. Will investigate.

However, I am puzzled why in any of platforms it is trying to build with the replacement library.

On Windows I am also seeing:

```
..\lib\include\elements/view.hpp(17): fatal error C1083: Cannot open include file: 'boost/asio.hpp': No such file or directory
```

**Comment by dmacvicar** [comment]
>However, I am puzzled why in any of platforms it is trying to build with the replacement library.

```
The CXX compiler identification is GNU 7.5.0
```

This explains a lot. The _Github_ runner preinstalls lot of "newer" software, but we need to point _cmake_ to it, as by default, _Ubuntu_ ships with very ancient stuff, and locally I am using _openSUSE Tumbleweed_ which has very recent everything.

**Comment by dmacvicar** [comment]
@djowel  Ok. The errors we have left is because the json library still depends on boost filesystem.

**Comment by djowel** [comment]
> @djowel Ok. The errors we have left is because the json library still depends on boost filesystem.

I see. How do you propose we proceed? Are you going to have a PR for that as well so it can propagate outwards? I can do that of course, but I am in the middle of something, so it might take time.

**Comment by djowel** [comment]
Hmm, how about we move the filesystem workaround to infra? That way json, artist and elements can just use it. We can move infra in a submodule as well, like I did in artist, referring to it by include file only. Thoughts?

**Comment by djowel** [comment]
Meantime, I'll fix develop.

**Comment by djowel** [comment]
> Hmm, how about we move the filesystem workaround to infra? That way json, artist and elements can just use it. We can move infra in a submodule as well, like I did in artist, referring to it by include file only. Thoughts?

OK, I am doing it anyway, starting from infra then json. I think it makes sense to have these as submodules. I'll need it to fix develop. Let's see how it goes...

**Comment by djowel** [comment]
Develop should be good now. See 115dca5dfbda41f81bc26d72f9c1561cb01fb6a6.

**Comment by dmacvicar** [comment]
> > @djowel Ok. The errors we have left is because the json library still depends on boost filesystem.
> 
> I see. How do you propose we proceed? Are you going to have a PR for that as well so it can propagate outwards? I can do that of course, but I am in the middle of something, so it might take time.

I will submit a PR that uses std:: or ghc:: later. I will make sure it uses the ghc from infra.

**Comment by djowel** [comment]
Oh, and I think we can remove the need to checkout infra and json from the C.I. scripts now. I also adjusted the cmake scripts. infra and json are now just submodules.

**Comment by djowel** [comment]
Hi @dmacvicar 

For some reason the Windows build could not find boost in this commit:
https://github.com/cycfi/elements/runs/608726683?check_suite_focus=true

Do you have an idea what's going on? There were no changes to cmake in that commit, just code changes. The commit before that is fine.

BTW, is there a way to contact you vis email, private message or something else?

**Pull request merged**
