### PR TITLE
Replace boost::filesystem with std::filesystem

### PR DESCRIPTION
**Pull request by dmacvicar**
(Associated PR https://github.com/cycfi/json/pull/2 )

This PR replaces the dependency on _boost::filesystem_ with _std::filesystem_, allowing to rely only on the header parts of boost.

### CODE REVIEW

**Comment by djowel** [comment]
I have some comments in https://github.com/cycfi/json/pull/2. I think this should be applied on an case-by-case basis using #ifdefs . Some compilers versions do not have std::filesystem in std.

**Comment by djowel** [comment]
Oh and glad to see CI working! :-)

**Comment by djowel** [comment]
BTW, moved target to develop

**Comment by djowel** [comment]
BTW, this: https://github.com/gulrak/filesystem might be our way to remove boost dependency altogether. It's header only "without other C++17 dependencies". I'm going to try it out with the "artist" library currently WIP.

**Comment by djowel** [comment]
> BTW, this: https://github.com/gulrak/filesystem might be our way to remove boost dependency altogether. It's header only "without other C++17 dependencies". I'm going to try it out with the "artist" library currently WIP.

OK, it works like a charm. While I'm at it, in the "artist" lib, also removed the need to clone infra. It looks really nice. I think it makes sense to do the same in the elements lib.

**Comment by dmacvicar** [comment]
> > BTW, this: https://github.com/gulrak/filesystem might be our way to remove boost dependency altogether. It's header only "without other C++17 dependencies". I'm going to try it out with the "artist" library currently WIP.
> 
> OK, it works like a charm. While I'm at it, in the "artist" lib, also removed the need to clone infra. It looks really nice. I think it makes sense to do the same in the elements lib.

So that library acts as a compat library for older compilers, still being header only?
That sounds like a good solution. It would still use std::filesystem on capable compilers right?

Let me know what I can try to do around this. I can find some time one evening or weekends.

**Comment by djowel** [comment]
> So that library acts as a compat library for older compilers, still being header only?
> That sounds like a good solution. It would still use std::filesystem on capable compilers right?
> 
> Let me know what I can try to do around this. I can find some time one evening or weekends.

Precisely. Here's what I did with artist: https://github.com/cycfi/artist/blob/windows_port/lib/include/artist/detail/filesystem.hpp

ghc::filesystem is in its own submodule, and although it has cmake, I never bothered to add it with add_subdirectory. I simply added its include directory.

Oh I did the same for infra (make it a submodule and have its header path via cmake target_include_directories). Here's the header structure:

https://github.com/cycfi/artist/tree/windows_port/lib

**Comment by Xeverous** [comment]
> While I'm at it, in the "artist" lib, also removed the need to clone infra. It looks really nice. I think it makes sense to do the same in the elements lib.

So, changing infra's `clamp/clamp_min/clamp_max` to `std::clamp/min/max`? :)

**Comment by djowel** [comment]
> > While I'm at it, in the "artist" lib, also removed the need to clone infra. It looks really nice. I think it makes sense to do the same in the elements lib.
> 
> So, changing infra's `clamp/clamp_min/clamp_max` to `std::clamp/min/max`? :)

I think you misunderstood what I said. No, that is not the only use of infra. Infra stays, but as a submodule.

**Comment by djowel** [comment]
> > > While I'm at it, in the "artist" lib, also removed the need to clone infra. It looks really nice. I think it makes sense to do the same in the elements lib.
> > 
> > 
> > So, changing infra's `clamp/clamp_min/clamp_max` to `std::clamp/min/max`? :)
> 
> I think you misunderstood what I said. No, that is not the only use of infra. Infra stays, but as a submodule.

OK, so I did an investigation and indeed there's very little use of infra in elements (unlike some of the other libraries (e.g. Q audio dsp lib and QPlug audio plugin lib.)). The only uses are the clamps, `noncopyable` and `CYCFI_ASSERT`. So after thinking about it, reluctantly I'd say go for it. Let us remove the infra dependency:

`clamp/clamp_min/clamp_max` --> `std::clamp/max/min`
`CYCFI_ASSERT(x, msg)` --> assert(x && msg)
`noncopyable` --> c++11 ctor/assign `delete`

I said reluctantly because I am afraid of the proliferation of small common utilities later. For example, just yesterday, I added the template deleter function class in infra because it's becoming common to use static  custom `unique_ptr` deleters. On the other hand, I'd say I'll deal with that when it becomes too prevalent, like in the other libraries I have. Not now.

So if anyone wants to take on this, please do. I'll start with `artist`. @Xeverous and @dmacvicar , your intuitions are spot on!

**Comment by dmacvicar** [comment]
https://github.com/cycfi/elements/pull/81 for the filesystem part. If that one is better, this one can be closed, and the discussion review moved there.

I will see how difficult is to replace the other parts you mention then.

**Comment by djowel** [comment]
@dmacvicar What's up with the C.I. failures?

**Comment by dmacvicar** [comment]
I will investigate the CI failures in the develop branch. (https://github.com/cycfi/elements/pull/82)

This PR had dependencies in PR's to other git repositories, therefore its CI is not very relevant.

**Pull request closed without merging**
