### PR TITLE
Do not deinitialize the fontconfig library

### PR DESCRIPTION
**Pull request by jpcima**
#135

This skips deinitializing the fontconfig library.
It prevents crashes in a DAW which also use the system-wide fontconfig library.

- if the host application takes care of deinitializing fontconfig, it's fine and memory leaks should not occur.
- otherwise, it will be just a negligible leak of some hundreds kB, not cumulative when instances of Elements ui will be created and destroyed repeatedly.

### CODE REVIEW

**Comment by Xeverous** [comment]
I don't like such change:

- I would rather move all singletons upwards to the public API so they can be explictly instantiated (or not) by elements library users.
- The code after this commit leaves `git blame` in a state as if I wrote the RAII wrapper incorrectly. At this point the wrapper can be removed entirely as it does not implement what it was written for - RAII. This PR basically breaks a working class.

> it will be just a negligible leak of some hundreds kB, not cumulative when instances of Elements ui will be created and destroyed repeatedly

I dislike such argumentation. If had a project which used X-Y libraries, and if many or every of them went this way, I would be furious at all the sanitizers reports while trying to detect or fix bugs within my own code.

**Comment by jpcima** [comment]
Well yeah but the deal here, it's that fontconfig is clearly not a library that was designed to accept RAII, it lives by a C-inspired design that it should be global, attached to the lifetime of the application.

It's this problem that we have to live with design decisions made by others, and there is need of a practical working solution.
Regarding the wrapper class, your argument makes sense that it would lose its RAII vocation that it has previously, fine to rewrite it in another way as needed.

Btw, regarding the basic program `FcInit(); FcFfini();`.
The sanitizer shows allocations anyway, because fontconfig authors probably have not cared enough to take care of them.
```
==123770== HEAP SUMMARY:
==123770==     in use at exit: 18,612 bytes in 6 blocks
==123770==   total heap usage: 10,559 allocs, 10,553 frees, 3,450,025 bytes allocated
```

**Comment by jpcima** [comment]
New suggestion of fontconfig RAII wrapper. Only for `FcConfig`.

If the programmers wish to clean up the fontconfig global kilobytes, which I doubt it matters a lot, the program made with Elements can always be wrapped between `FcInit(); [...]; FcFini();`.

**Comment by djowel** [comment]
> Well yeah but the deal here, it's that fontconfig is clearly not a library that was designed to accept RAII, it lives by a C-inspired design that it should be global, attached to the lifetime of the application.

I'm with @jpcima on this. It does not really hurt for some resources to be tied to the lifetime of the application.

**Comment by djowel** [comment]
> New suggestion of fontconfig RAII wrapper. Only for `FcConfig`.
> 
> If the programmers wish to clean up the fontconfig global kilobytes, which I doubt it matters a lot, the program made with Elements can always be wrapped between `FcInit(); [...]; FcFini();`.

Please do. Anything that will prevent crashing a DAW is a good solution for me. A few global kilobytes does not matter!

**Pull request merged**
