### PR TITLE
Allow disabled checkboxes to be checked in code.

### PR DESCRIPTION
**Pull request by eisen**
This is for instances when a checkboxes should be checked but the user won't be able to uncheck it.

### CODE REVIEW

**Comment by djowel** [comment]
Could you expound a bit more on this PR, maybe with some screenshots. A use-case would be great to grasp the idea.

**Comment by eisen** [comment]
Sure. I added an example on the buttons example too. I'm building a tool to make it easier to build engines using Vulkan for for computer graphics researchers. During setup, there are extensions that the user can enable. And there are a few that need to be enabled no matter what. These extensions I want to be displayed as checked but disabled so the user can't uncheck them as they are required.

**Comment by eisen** [comment]
image

**Comment by djowel** [comment]
> Sure. I added an example on the buttons example too. I'm building a tool to make it easier to build engines using Vulkan for computer graphics researchers. During setup, there are extensions that the user can enable. And there are a few that need to be enabled no matter what. These extensions I want to be displayed as checked but disabled so the user can't uncheck them as they are required.

Wonderful!

**Pull request merged**
