### PR TITLE
Active dynamic list

### PR DESCRIPTION
**Pull request by johannphilippe**
List of the improvements for dynamic list : 
* Elements inside the list can now be active controls (it is recommanded that the user keeps pointers to created elements) and respond to clicks, keys, drag, scroll, cursor (...)
* Allows vertical and horizontal list `vdynamic_list` and `hdynamic_list`
* Composers are adapted as well `basic_vertical_cell_composer` and `basic_horizontal_cell_composer`
* `resize` method to dynamically resize the list 

What does not work : 
* making a vdynamic_list containing hdynamic_lists works a little bit. There are some errors in static context (inactive elements) and with active elements. In static contexts there seem to be some drawing issues (it draws fine, but not with proper data it seems). And with active elements, the user actions do not seem to propagate to the right widgets.  See `two_dimensional_list` example.

### CODE REVIEW

**Comment by djowel** [comment]
> * making a vdynamic_list containing hdynamic_lists works a little bit. There are some errors in static context (inactive elements) and with active elements. In static contexts there seem to be some drawing issues (it draws fine, but not with proper data it seems). And with active elements, the user actions do not seem to propagate to the right widgets.  See `two_dimensional_list` example.

I think I have an idea why. Are you also holding the inner dynamic list externally?

**Comment by johannphilippe** [comment]
I tried both keeping the internal hdynamic_lists in a `vector<element_ptr>` on user side  or not. It seems to lead to the same bugs.

**Comment by johannphilippe** [comment]
Also, the way to build `table_list` could be hidden in a class like this. 

```c++
#include <elements.hpp>
#include<iostream>
#include<vector>
using namespace cycfi::elements;
using namespace cycfi::artist;

// Main window background color
auto constexpr bkd_color = rgba(35, 35, 37, 255);
auto background = box(bkd_color);

class table_cell_composer
{
public:
    using composer_fn = std::function<element_ptr(size_t line, size_t index)>;
    table_cell_composer(size_t lines, size_t columns, composer_fn &&fn)
        : _num_lines(lines)
        , _num_columns(columns)
        , _composer(fn)
    {}
    element_ptr compose(size_t line, size_t col) {
        return _composer(line, col);
    }

    size_t lines() {return _num_lines;}
    size_t columns() {return _num_columns;}

private:
    size_t _num_lines, _num_columns;
    composer_fn _composer;
};

class table_list : public vdynamic_list
{
public:
    using table_composer_ptr = std::shared_ptr<table_cell_composer>;

    element_ptr line_maker(size_t line)
    {
      if(h_list[line].get() == nullptr)
      {
          auto h_composer = basic_horizontal_cell_composer(_table_composer->columns(), [&, line](size_t col) {return _table_composer->compose(line, col);});
          h_list[line] = share(hdynamic_list(h_composer));
      }
      return h_list[line];
    };

    table_list(table_composer_ptr ptr)
        : vdynamic_list(basic_vertical_cell_composer(ptr->lines(), [&](size_t line) {return line_maker(line);})),
          _table_composer(ptr),
          h_list(ptr->lines(), nullptr)
    {

    }




protected:
    table_composer_ptr _table_composer;
    std::vector<element_ptr> h_list;
};

int main(int argc, char* argv[])
{

   app _app(argc, argv, "Empty Starter", "com.johannphilippe.empty-starter");
   window _win(_app.name());
   _win.on_close = [&_app]() { _app.stop(); };

   size_t lines = 500;
   size_t columns = 100;

   std::vector<std::vector<element_ptr>> ptr_list(lines);
   for(size_t i = 0; i < lines; i++)
   {
       ptr_list[i].resize(columns, nullptr);
   }

   auto && make_cell = [&](size_t l, size_t c)
   {
       color cell_color = ((l % 2 == 0) ? colors::red : colors::blue).opacity(c % 2 == 0 ? 1.0 : 0.5);
       return share(limit({{100, 50}, {200, 100}},layer(
                              label(std::string(std::to_string(l) + "  " + std::to_string(c))),
                              rbox(cell_color, 6)
                              )));
   };


   table_cell_composer comp(lines, columns, make_cell);
   table_list l(share(comp));

   view view_(_win);


   view_.content(
               margin({10, 10, 10, 10},
                      scroller(
                          hold(share(l))
                          )
                      ),
               background
               );


   _app.run();
   return 0;
}

```

**Comment by djowel** [comment]
Super awesome! I'll go study the PR ASAP!

**Comment by johannphilippe** [comment]
Same as #288, it seems I used the artist branch directly. I should change that.

**Comment by johannphilippe** [comment]
Well, I had to do a bit of -force to reinit this branch on develop base. So it seems better now, but if there is a risk it creates a mess in git history I can just doing it in a more "clean" way in another branch/PR. Sorry for that, I'm learning

**Pull request merged**
