### PR TITLE
make LTO an explicit CMake option

### PR DESCRIPTION
**Pull request by Xeverous**

### CODE REVIEW

**Comment by Xeverous** [comment]
LTO with MinGW is more or less broken, but this commit is much better than any assumptions in the build recipe.

**Comment by Xeverous** [comment]
Amazing. Please read GCC build logs. You will be surprised, but this is actually a good thing for my case.

**Comment by djowel** [comment]
lto1: internal compiler error: in add_symbol_to_partition_1, at lto/lto-partition.c:153
Please submit a full bug report,

**Comment by Xeverous** [comment]
So what do we do with this now? IMO now it is even clearer that LTO should be an explicit option. Perhaps make it OFF by default?

**Comment by djowel** [comment]
That makes sense. But it seems clang is good, correct? So maybe on by default on clang?

**Comment by Xeverous** [comment]
I don't think so. Better be consistent and do not assume anything. IMO LTO should be an explicit, independent option just like `CMAKE_BUILD_TYPE`.

**Comment by djowel** [comment]
> I don't think so. Better be consistent and do not assume anything. IMO LTO should be an explicit, independent option just like `CMAKE_BUILD_TYPE`.

OK, you are right.

**Comment by Xeverous** [comment]
Changed default to OFF, now CI fully succeeds.

**Comment by djowel** [comment]
Many thanks, @Xeverous !

**Comment by Xeverous** [comment]
> Many thanks, @Xeverous !

I will probably work on modals today. Can you look into my tab prototype commit? Notebook is the most important thing for me now.

**Pull request merged**
