### PR TITLE
coverity.yml: Shell may only be a single command

### PR DESCRIPTION
**Pull request by Flole998**

### CODE REVIEW

**Comment by Flole998** [comment]
I'm still trying to figure out how to actually run this without merging it into master first...

**Comment by djowel** [comment]
Maybe just do it in master?

**Comment by Flole998** [comment]
Yeah it seems like there is no other option

**Comment by djowel** [comment]
Let's do it. I'll merge to master

**Comment by djowel** [comment]
> Let's do it. I'll merge to master

Done

**Comment by Flole998** [comment]
Now you can add the coverity secrets to the repo and try to run it. Let's see how it goes

**Comment by djowel** [comment]
Can you check this?

https://github.com/cycfi/elements/actions/runs/9641033364

image

**Comment by Flole998** [comment]
It's still missing the environment secret configuration. That's why it can't download and fails. You need to setup a new environment named Coverity with the token and email address you're seeing when you login to coverity (on the tab where you can submit a build).

**Comment by djowel** [comment]
I am a total moron with Coverity. Is there a tutorial on how to set this up?

**Comment by djowel** [comment]
Working: https://github.com/cycfi/elements/actions/runs/9704773826

**Comment by djowel** [comment]
Now where do we get the results?

**Comment by Flole998** [comment]
Log in to coverity and you should be able to see it there (and also give others permission to see the results, I've sent a request that you can approve somewhere).

**Comment by djowel** [comment]
> Log in to coverity and you should be able to see it there (and also give others permission to see the results, I've sent a request that you can approve somewhere).

Approved.

**Comment by Flole998** [comment]
I had a brief look through the results, only a few high-severity issues which will only occur in corner cases (super long paths for example). Some of them I can't really assess (like the  "copy of large parameter") and some might be logical mistakes (the "dead code" ones). If you fix them they will disappear from the list after the next scan. There is a limited number of scans per week available,.it depends on the lines of code in the project. I'm not sure about the exact limits, I think even for the largest projects it's 3 runs per week. Just keep tuat in mind and don't run it after every commit or you'll have to wait until the week is over for the next analysis to run :)

**Comment by djowel** [comment]
> Thanks, I had a brief look through the results, only a few high-severity issues which will only occur in corner cases (super long paths for example). Some of them I can't really assess (like the "copy of large parameter") and some might be logical mistakes (the "dead code" ones). If you fix them they will disappear from the list after the next scan. There is a limited number of scans per week available,.it depends on the lines of code in the project. I'm not sure about the exact limits, I think even for the largest projects it's 3 runs per week. Just keep tuat in mind and don't run it after every commit or you'll have to wait until the week is over for the next analysis to run :)

Splendid! Thanks for working in this, @Flole998 super much appreciated! 👍 👍 👍 👍 👍

**Pull request merged**
